---

name: OS Info
description: "Running a job to get OS information"

on:
  [push, workflow_dispatch]

jobs:
  test_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Version
        run: |
          echo "OS: $(lsb_release -d | cut -f2-)"
          echo "Kernel: $(uname -r)"