---

name: Secrets
description: 'Reading stored secrets from the GitHub repository'

on:
  push

jobs:
  read_secret:
    runs-on: ubuntu-latest
    steps:
      - name: weak_password_env ${{ secrets.WEAKPASS }}
        env:
          weakpass_env: ${{ secrets.WEAKPASS }}
        run: echo "$weakpass_env is a weak environment variable"
