---

name: GitHub Actions Ignore Branch Template
description: "Generic layout for a GitHub Action to ignore a branch"

on:
  push:
    branches:
      - '!jv[-_]**'

jobs:
  some-unique-job-name-here:
    runs-on: ubuntu-latest
    steps:
      - name: First Task Name Here
        run: echo This should not have exexuted for JV branches
